### ISSUE TITLE
before_destroy with prepend: true in Rails 4.1 is no longer needed

### ISSUE THREAD

**Issue by ghost** [rubocop-hq/rails-style-guide#120]
In Rails 4.1 following setup does no longer destroy child records when you call `#destroy` on parent and in before_destroy callback return false.

``` ruby
class Car < ActiveRecord::Base
  has_many :wheels, dependent: :destroy

  before_destroy do
    false
  end
end

class Wheel < ActiveRecord::Base
  belongs_to :car
end
```

I don't know where it got fixed but now the destroy process is either in one big transaction or in nested transactions with rollbacks properly propagating up. It can be seen in SQL logs.

Hoewer you still need to use `prepend: true` if you want to e.g. log destroyed childs in parent, because without it, the `dependent: :destroy` callback still gets executed before before_destroy callback so within before_destroy callback childs are already destroyed and can't be reached.

I also guess that `prepend: true` could has an performance advantage because when you destroy parent with it, no destroying of childs(and rollback then) even takes place.

I don't know if the `prepend: true` should stay in guides or not but the reason for it `# bad (roles will be deleted automatically even if super_admin? is true)` is no longer valid.

**Comment by pirj** [comment]
Not sure if it's still a problem with recent Rails.
