### ISSUE TITLE
For people stuck on Rails 3

### ISSUE THREAD

**Issue by agrimm** [rubocop-hq/rails-style-guide#159]
Would a Rails 3 version of the style guide make sense? Or maybe the style guide could mention which versions of Rails each style guide item applies to.

**Comment by bbatsov** [comment]
Or they can refer to older versions of the guide. When it was originally created it targeted Rails 3. Perhaps the final commit from this era simply has to be tagged and referred somewhere. This won't be ideal, but it's simple.

**Comment by pirj** [comment]
Closing as stale. I hope it's getting fewer and fewer people got stuck on Rails 3 over years.

**Comment by nicobrenner** [comment]
I believe there's still plenty of people stuck with Rails 3 (or older). I'm currently upgrading a rails 2.3 app to 3.0.20. There are whole companies dedicated just to upgrading rails (fastruby.io).

Just checked the commits and the guide starts at rails 3.1 anyways.
