### ISSUE TITLE
Thoughts about forbidding after_find and after_initialize

### ISSUE THREAD

**Issue by kapcod** [rubocop-hq/rails-style-guide#164]
In my company I inserted it as our own standard because it creates all sorts of issues:
1. Performance issues in case of bulk reading. Especially because .includes only loads associations after the after_find done.
2. Unintuitive - when you read line like Post.last you expect it to always work, run 1 quick query and return the post or nil. Instead it might run many queries or even break if there's exception in after_find.
3. Extremely hard to debug if there's a bug inside after_find (even more in after_initialize). 

Here's one issue that I had lately as example to it:
Rails has default functionality of returning 404 in case of ActiveRecord::RecordNotFound exception. 
Someone did SomeThing.find(invalid_id) in after_find.
Result - totally correct page always results in 404 without any reason. And it doesn't get recorded as exception because of this 404 handler.

**Comment by pirj** [comment]
This didn't receive much response.

>  SomeThing.find(invalid_id) ... results in 404 without any reason

It's hard for me to agree with this. There is a reason - an invalid id 😄
