### ISSUE TITLE
Prefer ActiveSupport#try! to ActiveSupport#try

### ISSUE THREAD

**Issue by m1foley** [rubocop-hq/rails-style-guide#173]
There is already a [rule](https://github.com/bbatsov/rails-style-guide#try-bang) preferring `&.` to `try!`, but I'd like to add an additional rule for users on Ruby < 2.3: prefer `ActiveSupport#try!` to `ActiveSupport#try`.

**Comment by bbatsov** [comment]
:+1: Makes sense.

**Comment by pirj** [comment]
Closing since Ruby < 2.3 is EOL.
