### ISSUE TITLE
How to avoid "Share no more than two instance variables"

### ISSUE THREAD

**Issue by ghost** [rubocop-hq/rails-style-guide#179]
I agree with [this](https://github.com/bbatsov/rails-style-guide#shared-instance-variables) but it makes confusing me. 
How to reduce variables or some links if I have a blog app like this?

``` ruby
class PostsController < ApplicationController
  def index
    @posts = Post.all.paginate(params[:page])
    @posts_shown_at_sidebar = Post.first(5)
    @recent_comments = Comment.first(5)
    @pages_shown_at_sidebar = Page.all
  end
end
```

**Comment by panasyuk** [comment]
@nzwsch, try using Presenter and Delegator patterns.
http://nithinbekal.com/posts/rails-presenters/
https://gist.github.com/somebox/5a7ebf56e3236372eec4

**Comment by andyw8** [comment]
Since the this issue's author no longer exists on GitHub, and @panasyuk gave some suggestions, I'm going to close this.
