### ISSUE TITLE
Rails app name convention?

### ISSUE THREAD

**Issue by agerber23** [rubocop-hq/rails-style-guide#182]
Hey, I'm not sure if this is mentioned anywhere - but is there any naming conventions of a rails app?

For example:

rails new blogapp vs rails new blog_app

**Comment by syndbg** [comment]
No conventions afaik.

**Comment by cesc1989** [comment]
I've never named a Rails application `something_app` neither `somethingApp` just `something`

**Comment by 14113** [comment]
It's just example. Emagine different example like: `john_snow` or `company_eshop`

**Comment by katgironpe** [comment]
Use just one word. We have maintained apps that were named like pokemon or a game but they are used by multiple millions. I recall Rails apps named `hummingbird` and `breakout`. These are pretty good projects. Just feeling nostalgic. Some of us name apps after people like `alan` after Alan Turing.

**Comment by pirj** [comment]
Thinking about a good name for an app is the last thing that anyone does, as it doesn't come into play at any meaningful moment. `Foo`, `HelloWorld`, `Things` or `MyApp` would all work just fine as far as I'm concerned.
