### ISSUE TITLE
Native ActiveModel::Model does the same thing of ActiveAttr gem?

### ISSUE THREAD

**Issue by luizs81** [rubocop-hq/rails-style-guide#186]
I guess that in Rails 4, with the introduction of `ActiveModel::Model`, we don't need to rely on the ActiveAttr gem anymore?

**Comment by Drenmi** [comment]
Yes. We use `ActiveModel::Model` exclusively for form objects in our day to day job, so agree with this.

**Comment by pirj** [comment]
Fixed in https://github.com/rubocop-hq/rails-style-guide/pull/276
