### ISSUE TITLE
Clarify Configuration Guidance

### ISSUE THREAD

**Issue by Undistraction** [rubocop-hq/rails-style-guide#193]
I think the guidance for configuration could do with some clarification. It is unclear from the guidance how gem initialisation code that is environment-specific should be handled. Obviously in an ideal world, there would be a single initialiser per gem and any differences would be supplied via envs, but in cases where there are more substantive differences, for example a gem should only be initialised in a certain environment or requires a different kind of initialisation, adding some guidance would be helpful.

**Comment by pirj** [comment]
It heavily depends on what gem it is. I.e. you don't submit errors from `development` to an error tracking service, and you don't upload coverage data to a central location except on CI in `test` environment.
It would be a quite lengthy read to describe all that, and I believe adding `and keep per-env configuration in config/environments/*.rb` to
```
Keep configuration that’s applicable to all environments in the config/application.rb file
```
would be slightly excessive.

**Comment by pirj** [comment]
I'm not sure if anything can/should be done here.
Please feel free to reopen, or better send a PR.
