### ISSUE TITLE
Revisit Numeric#inquiry rule

### ISSUE THREAD

**Issue by mentero** [rubocop-hq/rails-style-guide#199]
There is an example against Numeric#inquiry methods in https://github.com/bbatsov/rails-style-guide#inquiry that goes like:

``` ruby
# bad - Numeric#inquiry
0.positive?
0.negative?

# good
0 > 0
0 < 0
```

The problem is that the `positive?` and `negative?` predicates for Numeric got elevated to the Ruby core feature. It is also a default behaviour for rubocop to use those.

Briefly looking at http://api.rubyonrails.org/classes/Numeric.html doesn't give me a clear replacement for the example so maybe the part about `NumericInquiry` should be removed

**Comment by andyw8** [comment]
Looks like this was already resolved in #226.
