### ISSUE TITLE
Revisit Rails/DynamicFindBy

### ISSUE THREAD

**Issue by jcoyne** [rubocop-hq/rails-style-guide#208]
https://github.com/bbatsov/rails-style-guide#find_by

What is the justification for this?  Isn't the dynamic method more expressive? Why should the style guide tell you not to use a feature of the framework? http://guides.rubyonrails.org/active_record_querying.html#dynamic-finders

**Comment by olegykz** [comment]
http://edgeguides.rubyonrails.org/4_0_release_notes.html

> All dynamic methods except for find_by_... and find_by_...! are deprecated

**Comment by jcoyne** [comment]
> except for

**Comment by olegykz** [comment]
I'm not sure why they left find_by/find_by_...!, but AFAIK the main in issue with dynamic finders is that they based on **method_missing** ruby functionality with appropriate performance cost. IMHO, dynamic finders are less expressive and less readable that new finders API. But it's just IMHO :)

**Comment by KevinBongart** [comment]
@olegykz That's a fair point, and I'm on board with @jcoyne that the current guideline doesn't make sense without this information. It reads like `find_by_x` is a bad idea, whereas it's a trade-off that should be left to the developer.

I'd rather see the guideline giving a reason:

```ruby
# bad
User.where(first_name: 'Bruce', last_name: 'Wayne').first

# good, readable but relies on Ruby's method_missing, thus coming with a performance cost
# see related deprecations: http://edgeguides.rubyonrails.org/4_0_release_notes.html#active-record-deprecations
User.find_by_first_name_and_last_name('Bruce', 'Wayne')

# preferable
User.find_by(first_name: 'Bruce', last_name: 'Wayne')
```

**Comment by jcoyne** [comment]
@olegykz it's a one time performance cost (constant time), as they then define the method, which is then loaded in the method cache. This means there is no appreciable advantage in the time span for which a web-app would be up.  Clearly other people, by which I mean the Rails core team, feels differently about the usefulless of this functionality.

**Comment by olegykz** [comment]
@jcoyne unfortunately I can't find the discussion about this functionality deprecation. Maybe another disadvantage of dynamic finders usage is that they doesn't work with associations or it potentially was too complex to implement support of them, so they decide to support less functionality amount with more universality and API consistency.

**Comment by jcoyne** [comment]
@olegykz My problem here is that the rails-style-guide is not in harmony with the Rails committers.  If you think dynamic finders are a bad idea.  You should work to deprecate them in Rails, not make up rules in a style guide.  These two things should work well together, not be at odds with one another.

**Comment by olegykz** [comment]
@jcoyne I think the point of this concrete rules is based on experience of concrete persons. My experience is pretty same - if your queries become complex - you will have to leave dynamic finders. So it's simply preferable to not use it from beginning - just simple learning by someone's mistakes.

**Comment by lucianosousa** [comment]
I did the PR for this `find_by`.

The main reason for this was code readability and another *not important* was performance.
You guys can see the original discussion here:
https://github.com/bbatsov/rails-style-guide/pull/170

ps: I do think we should put an extra info on the guide like @KevinBongart mention, I didn't because it was discussed on the PR.

cheers

**Comment by jcoyne** [comment]
@lucianosousa You say "The main reason for this was code readability and another not important was performance." but the reason you cited in your PR was a benchmark.

**Comment by lucianosousa** [comment]
@jcoyne at the beginning. if you read all discussion you will see that the merge happened for another reason

**Comment by pirj** [comment]
Everything seems to have been addressed.
Please feel free to send a PR if you feel something was left out.
