### ISSUE TITLE
Unexpected behavior of query attribute methods

### ISSUE THREAD

**Issue by dpisarewski** [rubocop-hq/rails-style-guide#216]
Query attribute methods behave unexpectedly for the majority of developers. Everybody thinks they are just shortcuts for attribute.present?. It the reality the logic is more complex and inconsistent. They return false for zero values if the attribute's table column is numeric and false for values like 0, '0', 'off', etc. if the attribute has no table column.

Since changing the behavior of these methods can break applications, we can either add a deprecation warning into rails or add a cop here.

See issue: https://github.com/rails/rails/issues/28438
Implementation: https://github.com/rails/rails/blob/v4.2.6/activerecord/lib/active_record/attribute_methods/query.rb#L10-L31

And some articles about query attribute methods:
https://rails-bestpractices.com/posts/2010/10/03/use-query-attribute/
http://blog.plataformatec.com.br/2012/05/active-record-attribute-method/

**Comment by pirj** [comment]
Closing as this didn't get much feedback, and it's not too clear what the guide should recommend exactly.
