### ISSUE TITLE
rails best practice for validating user submitted params?

### ISSUE THREAD

**Issue by blairanderson** [rubocop-hq/rails-style-guide#229]
I have often seen rails controllers have dozens of lines of code related to cleaning and validating search params. 

For example if a CMS is toggling between `draft` and `published` posts:

```ruby
all_types = ["draft", "published"]

view_param = params[:status].to_s

params[:status] = if view_param.present? && view_param.in?(all_types)
                    view_param
                  else
                    "draft"
                  end

@posts = Post.where("lists.status = ?", params[:status])
```

Your user wants to be able to toggle back and forth with a url param, and you want to have a default. 

Would be great to see a discussion about how people do this consistently with different patterns and multiple developers.

**Comment by st0ck** [comment]
I don't know any beautiful solution for this case but if think of a short one...
```
all_types = ["draft", "published"]

def permitted_params
  params.require(...).permit(...).tap do |whitelisted| 
    whitelisted[:status] = ([params[:status]] & all_types).first || 'draft'
  end
end
```

`require` and `permit` could be deleted if strong parameters is not used in a project.

**Comment by blairanderson** [comment]
I am back 6 months later. still wondering... best. 

- clean
- works
- shows an error if user is messing with inspector

**Comment by pirj** [comment]
Maybe a model-only approach would work?
```ruby
class List < ApplicationRecord
  enum status: %i[draft published]
  scope with_status: ->(status) { where(status: status) }
end

class Post
  belongs_to :list
end

# controller
@posts = Post.joins(:list).merge(List.with_status(params[:status]))
```

**Comment by pirj** [comment]
There are many solutions to this problem, like e.g. form objects, `dry-*` in addition to the aforementioned approaches. There is no one true way.
This means a guideline would be controversial.
