### ISSUE TITLE
Naming convention Error

### ISSUE THREAD

**Issue by Sourabh-Deshmukh** [rubocop-hq/rails-style-guide#230]
class Post < ActiveRecord::Base
  has_many :comments
end

class Comments < ActiveRecord::Base
  belongs_to :post
end

# routes.rb
resources :posts do
  resources :comments
end

why class named comment is plural here. As per my knowledge, model name should be singular so as the class name.

**Comment by KevinBongart** [comment]
Hi @Sourabh-Deshmukh! If I understand, you're referring to the plural class name `Comments` in this section: https://github.com/rubocop-hq/rails-style-guide#routing

Good point. Do you want to update the README and open a pull request?

**Comment by pirj** [comment]
I could only find `class Comment` (singular) in https://github.com/rubocop-hq/rails-style-guide#nested-routes
This was most probably fixed at some point.
