### ISSUE TITLE
Don't use .to_time

### ISSUE THREAD

**Issue by RST-J** [rubocop-hq/rails-style-guide#233]
The section about [time](https://github.com/rubocop-hq/rails-style-guide#time) suggests not to use `Time.parse`. Rails core-extension `.to_time` for the `String` class also returns `Time`, so I think the use of `.to_time` should also be discouraged.

**Comment by KevinBongart** [comment]
> Rails core-extension `.to_time` for the `String` class also returns `Time`

**Comment by KevinBongart** [comment]
> Rails core-extension `.to_time` for the `String` class also returns `Time`

How does this discourage against using `String#to_time`? On the contrary, it seems like Rails supports it

**Comment by RST-J** [comment]
Ah, I see. The point is not primarily the return type but how the input is interpreted. I mistakenly thought that belongs together.

However, the given reason not to use `Time.parse` is that it interprets the given time in the system's time zone.
```ruby
# bad => Will assume time string given is in the system's time zone.
Time.parse('2015-03-02 19:05:37')
```
And `String.to_time` does exactly the same by default (or when given `:local` as parameter). It does not obey the configured time zone.

**Comment by pirj** [comment]
This makes sense
```
# bad
Time.parse("13-12-2012") # => 2012-12-13 00:00:00 +0400
# bad as well 
"13-12-2012".to_time # => 2012-12-13 00:00:00 +0400
# good
Time.zone.parse("13-12-2012") # => Thu, 13 Dec 2012 00:00:00 EST -05:00
```

Will you please send a pull request?
