### ISSUE TITLE
Avoid creating additional environments?

### ISSUE THREAD

**Issue by andyw8** [rubocop-hq/rails-style-guide#240]
> Create an additional `staging` environment that closely resembles the `production` one.

It sounds like this is advocating for adding a new config with `config/environments`. This is counter to the advice in https://12factor.net/config

> In a twelve-factor app, env vars are granular controls, each fully orthogonal to other env vars. They are never grouped together as “environments”, but instead are independently managed for each deploy. This is a model that scales up smoothly as the app naturally expands into more deploys over its lifetime.

From experience, when there are multiple environments (beyond the base 3), they often diverge, which lead to problems.

**Comment by bbatsov** [comment]
I agree. The use of a staging environment used to be come when I first wrote this, but today there are no good excuses for having it.
