### ISSUE TITLE
Find more editors

### ISSUE THREAD

**Issue by bbatsov** [rubocop-hq/rails-style-guide#243]
Lately I've had little time to maintain the guide and it'd be great if we managed to enlist a few extra editors to polish and update it. @andyw8's recent contributions reminded me it's time to tackle this. 

@andyw8 Are you interested in joining the editor team? :-)

**Comment by andyw8** [comment]
Yes, I would be interested, but I think there should be a group of editors (at least 3) to ensure a common consensus.

**Comment by bbatsov** [comment]
I agree. That's why I'm nominating also @koic and @pirj for editors. And I'll be around from time to time as well. :-)

**Comment by bbatsov** [comment]
Btw, @andyw8 and co - feel free to cleanup the Ruby guide's backlog as well if you're feeling extra adventurous. :D

**Comment by pirj** [comment]
I guess we can nominate someone who will be active in issues/pull requests going forward.
