### ISSUE TITLE
Question about "Single-attribute Validations" topic

### ISSUE THREAD

**Issue by iago-silva** [rubocop-hq/rails-style-guide#258]
[Current example](https://rails.rubystyle.guide/#single-attribute-validations):

```ruby
# bad
validates :email, :password, presence: true
validates :email, length: { maximum: 100 }

# good
validates :email, presence: true, length: { maximum: 100 }
validates :password, presence: true
```

if bad example would be like this:

```ruby
# bad
validates :email, :password, presence: true
```
would the good one be like this?

```ruby 
# good
validates :email, presence: true
validates :password, presence: true
```

**Comment by pirj** [comment]
Yes. One reason off the top of my head - for grouping validations by attribute:
```ruby
validates :email, presence: true,
  uniqueness: true,
  length: { maximum: 128 }
validates :password,
  presence: true,
  length: { minimum: 8 }
```
Not too much in common once you've added a couple of validations to those attributes.

You can group validations with similar parts with [`with_options`](https://api.rubyonrails.org/v6.1.3/classes/Object.html#method-i-with_options):
```ruby
  with_options if: :persisted?, length: { minimum: 50 } do
    validates :content, allow_blank: true
    validates :description
  end
```
but [Rails Guides only recommend doing this for conditional validation only](https://guides.rubyonrails.org/active_record_validations.html#grouping-conditional-validations), not for arbitrary options, even though it is possible.
