### ISSUE TITLE
Clarify No Direct Model View

### ISSUE THREAD

**Issue by asavageiv** [rubocop-hq/rails-style-guide#272]
Why shouldn't the model layer ever be called directly by the view? If I have a data on a model like `Car#make` should I not call `car.make` from a view to show it in the UI? Why not? Or does this mean "Don't call mutation methods directly on the model from the view"?

**Comment by pirj** [comment]
> Never call the model layer directly from a view.

It means that you shouldn't call `Car.find(params[:car_id])`. Agree, it's a subject for interpretation. A pull request is welcome.

On a side note, there's another guideline describing this from a different angle:

https://github.com/rubocop-hq/rails-style-guide#model-business-logic

> Unless they have some meaning in the business domain, don’t put methods in your model that just format your data (like code generating HTML). These methods are most likely going to be called from the view layer only, so their place is in helpers. Keep your models for business logic and data-persistence only.
