### ISSUE TITLE
Missing `config.load_defaults`

### ISSUE THREAD

**Issue by pirj** [rubocop-hq/rails-style-guide#277]
It took me by surprise that if you don't explicitly specify:
```ruby
config.load_defaults 5.2
```
on a Rails 5.2 project, **no** defaults will be loaded, e.g. `config.active_record.belongs_to_required_by_default` will be `nil` and will be treated as `false`. It is `true` since Rails 5.0.

Not specific to Rails 5.2.

Is it worth it adding to the guide?

**Comment by koic** [comment]
Sure! I think it's worth adding the config. It may be better to place it between `App Config` and` Staging Like Prod`.
https://github.com/rubocop-hq/rails-style-guide#app-config

In future it will be possible to make cop to check for existence of `config.load_defaults`.
