### ISSUE TITLE
find_by throwing warning on arbitrary method

### ISSUE THREAD

**Issue by andresespinosapc** [rubocop-hq/rails-style-guide#278]
I created a method `find_by_params` in a controller to get params associated with a `find_by` method/endpoint. Rubocop says `Use 'find_by' instead of dynamic 'find_by_params'`, but it's not a model's method.

**Comment by pirj** [comment]
I suggest you open a ticket in https://github.com/rubocop-hq/rubocop-rails/issues/new
You can even draft a PR with a failing spec covering your case.
