### ISSUE TITLE
when to use parentheses

### ISSUE THREAD

**Issue by sfjuggernaut** [rubocop-hq/rails-style-guide#31]
I like the guideline around "Omit parentheses around parameters for methods that are part of an internal DSL". This is pretty straight forward for most of the main app code. What have people found for the following....

testing:
- creating your own DSL for testing
- using Capybara - their own examples bounce back and forth (see: http://rubydoc.info/github/jnicklas/capybara/master/Capybara/Node/Actions)
- factory girl: Factory(:user) vs. Factory :user

views:
- link_to
- form_for / form_tag
- submit_tag
- etc.

**Comment by andyw8** [comment]
I think this is a good question, but since there have been no replies on this issue for 7 years, it seems there is no community consensus.

**Comment by pirj** [comment]
Not sure if `Factory.create :user` is a DSL, looks more like an ordinary method call.

**Comment by bbatsov** [comment]
For me it's a regular method, which should be parenthesized.
