### ISSUE TITLE
quote email addresses

### ISSUE THREAD

**Issue by paulschreiber** [rubocop-hq/rails-style-guide#35]
The guide suggests this:
    # in your mailer class
    default from: 'Your Name info@your_site.com'

However, that doesn't work if your name contains characters such as commas. This is commonly used for organizational emails, i.e. Joe Smith, MyOrg info@site.com.

Using quotes solves this problem:
"\"Your Name\" info@your_site.com"

**Comment by pirj** [comment]
Closing as stale.

Pull request is welcome. I would love to see a failure trace if it's still the case
