### ISSUE TITLE
Defaulting boolean attributes to true

### ISSUE THREAD

**Issue by garyv** [rubocop-hq/rails-style-guide#43]
I was wondering what the best way is to make an Active Record attribute default to true.

This guide recommends setting defaults in the model, not the migration 
https://github.com/bbatsov/rails-style-guide#migrations

But this technique fails when defaulting a boolean to true.

```
def allow_robots
  self[:allow_robots] or true
end
```

In the code above, allow_robots will always evaluate to true, even if set to false in Active Record. At the very least, there should be a short disclaimer in the guide about the technique not working in this case. But I'd prefer to arrive at a recommended solution.

This variation of the method will get the desired result.

```
def allow_robots
  !self[:allow_robots].nil? ? self[:allow_robots] : true 
end
```

At this point, the code's purpose is much less obvious, and defaulting in the migration is starting to look pretty by comparison.

```
def change
  add_column :settings, :allow_robots, :boolean, :default => true
end
```

Any thoughts? I feel like there's probably a better way to default true that I just haven't thought of yet.

**Comment by pirj** [comment]
I believe this was addressed in https://github.com/rubocop-hq/rails-style-guide/pull/275
