### ISSUE TITLE
Order of includes and scopes?

### ISSUE THREAD

**Issue by kbighorse** [rubocop-hq/rails-style-guide#65]
In the case of a model with a default_scope, includes, and other scopes, what should the order be? Includes, then default scope, then scopes below in the 'other macros' section would be my guess. Also, in my opinion, scopes should be first-class citizens in the macro-ordering section, along with attribute macros, validations, etc.

**Comment by lleolin** [comment]
I'd like to know how one is to order scopes.

**Comment by pirj** [comment]
This is pretty much covered in https://rails.rubystyle.guide/#macro-style-methods
Delegates seem to be missing, however, I believe, it's implied that they should be somewhere around attributes.
Please feel free to send a PR to extend this if you feel it's not descriptive enough.
