### ISSUE TITLE
Internationalization keys naming conventions

### ISSUE THREAD

**Issue by guilhermesimoes** [rubocop-hq/rails-style-guide#71]
What names do you give to the keys in the I18n yaml files? For example:
1. A link to a products index. `products_link`?
2. A link that destroys a product? `destroy_link`? `link_to_destroy`?
3. What if the destroy action has a confirm prompt? Do you add 2 keys to the key `destroy_link` like `text` (the actual text of the link) and `confirm` (the text of the confirm prompt)?
4. Paragraphs in an about section. `p1`, `p2` and so on?

**Comment by andyw8** [comment]
@guilhermesimoes I think it's very hard to give specific advice here. Since there has been no other comments in 6 years, I'm going to close this, but feel free open a new issue if you have something to propose.
