### ISSUE TITLE
Working with date/time 

### ISSUE THREAD

**Issue by arr-dev** [rubocop-hq/rails-style-guide#94]
I can't find in the guide anything related to working with Date/Time and time zones.

Something like the Cheat sheet at the bottom of http://www.elabs.se/blog/36-working-with-time-zones-in-ruby-on-rails would be great, or at least a link to the article.

**Comment by bbatsov** [comment]
I've finally started working on this https://github.com/bbatsov/rails-style-guide#time

Help welcome! :-)

**Comment by andyw8** [comment]
Since the guide now contains a Time section, I think this can be closed.

https://github.com/rubocop-hq/rails-style-guide#time
